package practica2;

import java.awt.Color;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JOptionPane;


public class Practica2 extends javax.swing.JFrame {

    private Steep[] steeps = new Steep[100];
    private int iter=0,iterShow;
    
    public Practica2() {
        initComponents();
    }

    private String round(double number){
        BigDecimal bd = new BigDecimal(number);
        bd = bd.setScale(2, RoundingMode.HALF_UP);
        
        return bd.toString();
    }
    
    private void addSteep(Steep steep){
            
        steeps[iter] = steep;
        
        iter++;
        iterShow=iter-1;
    }

    private void clearCells(){
        dolares.setBackground(Color.white);
        euros.setBackground(Color.white);
    }
    
    private void showPast(){
        
        if(iterShow==iter){
            clearCells();
        }else if(iterShow == 0){
            iterShow = 5;
            euros.setText(steeps[iterShow].getEuro());
            dolares.setText(steeps[iterShow].getDolar());
        }else {
            iterShow--;
            euros.setText(steeps[iterShow].getEuro());
            dolares.setText(steeps[iterShow].getDolar());
        }
    }
     
    private class Steep{
        private final String dolar;
        private final String euro;

        public Steep(String euro, String dolar) {
            this.dolar = dolar;
            this.euro = euro;
        }
        public String getDolar() {
            return dolar;
        }
        public String getEuro() {
            return euro;
        }       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        euros = new javax.swing.JTextField();
        dolares = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        equivalecia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Euro(€)");

        jLabel2.setText("Dolar($USA)");

        euros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eurosMouseClicked(evt);
            }
        });
        euros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });

        dolares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dolaresMouseClicked(evt);
            }
        });

        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("CONVERSOR");

        jButton2.setText("Past");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        equivalecia.setName("equivalencia"); // NOI18N
        equivalecia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equivaleciaMouseClicked(evt);
            }
        });

        jLabel4.setText("Equivalencia $USA para 1€");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(equivalecia, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(euros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(dolares, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equivalecia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(euros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dolares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(53, 53, 53))
        );

        equivalecia.getAccessibleContext().setAccessibleName("equivalencia");
        jLabel4.getAccessibleContext().setAccessibleName("Equivalencia $USA a 1€");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        double eur=1.17, dol=0.85, unit, result;
        String eurString, dolString;
        
        try{
            if(!equivalecia.getText().equals("")){
                String data = equivalecia.getText();
                dol = Double.parseDouble(data);
                eur = 1/dol;
            }
            if(!euros.getText().equals("")){
                String data = euros.getText();
                unit = Double.parseDouble(data);
                result = unit*eur;
                
                dolString=round(result);
                eurString=round(unit);
                
                dolares.setBackground(Color.green);
                
            }else if (!dolares.getText().equals("")){
                String data = dolares.getText();
                unit = Double.parseDouble(data);
                result = unit*dol;
                
                dolString=round(unit);
                eurString=round(result);
                
                euros.setBackground(Color.green);
            }else{
                dolString=round(dol);
                eurString=round(eur);
                
                euros.setBackground(Color.green);
                dolares.setBackground(Color.green);
            }
            
            euros.setText(eurString);
            dolares.setText(dolString);
            
            addSteep(new Steep(eurString, dolString));
            
        } catch(NumberFormatException e){
            euros.setText("");
            dolares.setText("");
            clearCells();
            JOptionPane.showMessageDialog(this,"Introducir solo números","Alert",JOptionPane.ERROR_MESSAGE);     
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void eurosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eurosMouseClicked
        dolares.setText("");
        clearCells();
    }//GEN-LAST:event_eurosMouseClicked

    private void dolaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dolaresMouseClicked
        euros.setText("");
        clearCells();
    }//GEN-LAST:event_dolaresMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if(iterShow<1){
            clearCells();
            euros.setText("");
            dolares.setText("");
        }else{
            clearCells();
            iterShow--;
            euros.setText(steeps[iterShow].getEuro());
            dolares.setText(steeps[iterShow].getDolar());            
        }     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(iterShow>=iter){
            clearCells();
            euros.setText("");
            dolares.setText("");
        }else{
            clearCells();
            euros.setText(steeps[iterShow].getEuro());
            dolares.setText(steeps[iterShow].getDolar());
            iterShow++;
        }     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

    private void equivaleciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equivaleciaMouseClicked
        clearCells();
        euros.setText("");
        dolares.setText("");
    }//GEN-LAST:event_equivaleciaMouseClicked

   
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dolares;
    private javax.swing.JTextField equivalecia;
    private javax.swing.JTextField euros;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
